version: "3"

services:
  terraform:
    image: hashicorp/terraform:0.12.29
    volumes:
      - ~/.aws:/root/.aws:ro
      - ./:/workdir
    working_dir: "/workdir"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_PROFILE
